baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Snail Kites in Florida'

[menus]
  # [[menus.main]]
  # name = "Home"
  # url = "/"
  # weight = 1
  [[menus.main]]
  name = "About"
  identifier = "about"
  url = "#"
  weight = 1

    [[menus.main]]
    name = "Mission"
    parent = "about"
    url = "/mission/"
    weight = 1

    [[menus.main]]
    name = "People"
    parent = "about"
    url = "/people/"
    weight = 2

    [[menus.main]]
    name = "Cooperators"
    parent = "about"
    url = "/cooperators/"
    weight = 3

[[menus.main]]
  name = "Learn"
  identifier = "learn"
  url = "#"
  weight = 2

    [[menus.main]]
    name = "Facts"
    parent = "learn"
    url = "/facts/"
    weight = 1

    [[menus.main]]
    name = "History"
    parent = "learn"
    url = "/history/"
    weight = 2

    [[menus.main]]
    name = "Identification"
    parent = "learn"
    url = "/identification/"
    weight = 3

  [[menus.main]]
  name = "Research"
  identifier = "research"
  url = "/#/"
  weight = 3

    [[menus.main]]
    name = "Monitoring"
    parent = "research"
    url = "/research/monitoring/"
    weight = 1

    [[menus.main]]
    name = "Publications"
    parent = "research"
    url = "/publications/"
    weight = 2


  [[menus.main]]
  name = "Gallery"
  identifier = "gallery"
  url = "/gallery/"
  weight = 4

  [[menus.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
